apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: kubes-trial
build:
  artifacts:
  - image: ahmetuzgor/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
  - image: ahmetuzgor/posts
    context: posts
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - config-deployment.yaml
    - config-service.yaml
    - config.yaml
    - event-bus-deployment.yaml
    - ingress-service.yaml
